=== eDatos/notifications/etc/rest/internal/metamac-notifications-rest-internal-domain-v1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.siemac.org/metamac/rest/notifications/v1.0/domain" xmlns:tns="http://www.siemac.org/metamac/rest/notifications/v1.0/domain"
    xmlns:common="http://www.siemac.org/metamac/rest/common/v1.0/domain">

    <xs:import namespace="http://www.siemac.org/metamac/rest/common/v1.0/domain" schemaLocation="metamac-rest-api:metamac-rest-common-domain-v1.0.xsd" />

    <xs:complexType name="Notification">
        <xs:sequence>
            <xs:element name="id" type="xs:string" />
            <xs:element name="urn" type="xs:string" />
            <xs:element name="selfLink" type="common:ResourceLink" />
            <xs:element name="parentLink" type="common:ResourceLink" />
            
            <xs:element name="sendingApplication" type="xs:string" minOccurs="1"/>
            <xs:element name="sendingUser" type="xs:string" minOccurs="0"/>
            <xs:element name="sendingDate" type="xs:dateTime" minOccurs="0"/>
            <xs:element name="email" type="xs:string" minOccurs="0"/>
            <xs:element name="notificationType" type="tns:NotificationType" minOccurs="1"/>
            <xs:element name="notificationConditionType" type="tns:NotificationConditionType" minOccurs="0"/>
            <xs:element name="expirationDate" type="xs:dateTime" minOccurs="0"/>
            <xs:element name="role" type="xs:string" minOccurs="0"/>
            <xs:element name="statisticalOperation" type="common:Resource" minOccurs="0"/>
            <xs:element name="message" type="xs:string" minOccurs="1"/>
            <xs:element name="receivers" type="tns:Receivers" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="kind" type="xs:string" use="required" />
    </xs:complexType>
    
    <xs:complexType name="Receiver">
        <xs:sequence>
            <xs:element name="username" type="xs:string" />
        </xs:sequence>
    </xs:complexType>  
    
    <xs:complexType name="Receivers">
        <xs:sequence>
            <xs:element name="receiver" type="tns:Receiver" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="total" type="xs:unsignedLong" use="required"/>
    </xs:complexType>         
    
    
    <!-- Enums -->
    <xs:simpleType name="NotificationType">
        <xs:restriction base="xs:token">
            <xs:enumeration value="NOTIFICATION" />
            <xs:enumeration value="ADVERTISEMENT" />
        </xs:restriction>
    </xs:simpleType>
    
     <xs:simpleType name="NotificationConditionType">
        <xs:restriction base="xs:token">
            <xs:enumeration value="APPLICATION_ACCESS" />
            <xs:enumeration value="STATISTIC_OPERATION_ACCESS" />
            <xs:enumeration value="ROLE_ACCESS" />
        </xs:restriction>
    </xs:simpleType>   
    
    <!-- **************** ELEMENTS **************** -->
    <xs:element name="notification" type="tns:Notification"/>
     
</xs:schema>

=== eDatos/notifications/metamac-notifications-rest-internal-impl/src/test/resources/responses/notifications/putNotification.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<notice:notification
	xmlns:notice="http://www.siemac.org/metamac/rest/notifications/v1.0/domain"
	xmlns:cdomain="http://www.siemac.org/metamac/rest/common/v1.0/domain"
    xsi:schemaLocation="http://www.siemac.org/metamac/rest/notifications/v1.0/domain metamac-notifications-rest-internal-domain-v1.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<notice:sendingApplication>application</notice:sendingApplication>
	<notice:sendingUser>user</notice:sendingUser>
	<notice:email>user@domain.com</notice:email>
	<notice:notificationType>NOTIFICATION</notice:notificationType>
	<notice:expirationDate>2013-11-11T12:15:08.606Z</notice:expirationDate>
	<notice:role>ADMIN</notice:role>
	<notice:statisticalOperation kind="operations#operation">
		<cdomain:id>operation01</cdomain:id>
		<cdomain:urn>urn:siemac:org.siemac.metamac.infomodel.statisticaloperations.Operation=operation01
		</cdomain:urn>
		<cdomain:selfLink kind="operations#operation"
			href="http://domain.com/metamac-statistical-operations-web/apis/operations-internal/v1.0/operations/operation01" />
		<cdomain:name>
			<cdomain:text xml:lang="es">operation01 en EspaÃ±ol
			</cdomain:text>
			<cdomain:text xml:lang="en">operation01 in English
			</cdomain:text>
		</cdomain:name>
	</notice:statisticalOperation>
	<notice:messages>
        <notice:message>
            <notice:text>My message</notice:text>
        </notice:message>
    </notice:messages>
	<notice:receivers total="5">
		<notice:receiver>
			<notice:username>user-0</notice:username>
		</notice:receiver>
		<notice:receiver>
			<notice:username>user-1</notice:username>
		</notice:receiver>
		<notice:receiver>
			<notice:username>user-2</notice:username>
		</notice:receiver>
		<notice:receiver>
			<notice:username>user-3</notice:username>
		</notice:receiver>
		<notice:receiver>
			<notice:username>user-4</notice:username>
		</notice:receiver>
	</notice:receivers>
</notice:notification>
